name: ci

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Installing PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "8.2"
        ini-values: memory_limit=-1

    - name: "Install composer dependencies"
      uses: "ramsey/composer-install@v2"

    - name: "Run ci script"
      run: "composer ci"
