name: ci

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: "root"
          POSTGRES_DB: "app"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: "Installing PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "8.3"
        ini-values: memory_limit=-1

    - name: "Install composer dependencies"
      uses: "ramsey/composer-install@v2"

    - name: "Run ci script"
      run: "composer ci"
      env:
        DATABASE_URL: postgresql://root:password@localhost/app?serverVersion=16&charset=utf8
